server:
  port: 9999 
management:
  port: 9998

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    
turbine:
  aggregator:
    clusterConfig: ORDER,CUSTOMER
  appConfig: order,customer
  clusterNameExpression: metadata['default']
  amqp:
    port: 9997

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672


#logging:
#  level:
#    com.netflix.turbine: 'TRACE'
#
#
