server:
  port: 9999 
  
management:
  port: 9998

spring:
  application:
    name: turbine-server

  rabbitmq:
    host: 127.0.0.1
    port: 5672


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/    
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    
#turbine:
#  aggregator:
##    clusterConfig: ORDER,CUSTOMER
# # appConfig: order,customer
#  clusterNameExpression: metadata['default']
#  amqp:
#    port: 9997



#logging:
#  level:
#    com.netflix.turbine: 'TRACE'
#
#
