server:
  port: 8761

spring:
  application:
    name: eureka
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyncEmpty: 0