server:
  port: 8000

spring:
  application:
    name: producer
  cloud:
    config:
      uri: http://localhost:8888
  rabbitmq:
    host: 127.0.0.1
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#eureka:
#  registerWithEureka: true
#  fetchRegistry: true
#  serviceUrl:
#     defaultZone: http://localhost:8761/eureka/
#  instance:
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}:${spring.application.instance_id}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
